### ISSUE TITLE
Bugged On Server

### ISSUE THREAD

**Issue by DaComeaux** [SFort/BeaconFlight#1]
Got this working 100% on single player worlds.

On my server it doesn't work.

Starting out of range of a beacon, flight is not granted. When I first get in range of a beacon, creative flight is still not granted, and attempting to double jump applies the slow falling effect. Then, when I leave the range of a beacon, creative flight is granted.  When I get back in range of a beacon, creative flight is removed, and the slow falling status effect is applied.

Tested with multiple accounts

**Comment by SFort** [comment]
i really hate that github doesn't automaticly subscribe you to forked repos. (saw it by luck).
Wierd I'll take a look

**Comment by SFort** [comment]
Can't replicate the issue.
what config are you using?
using any other mods?
